name: 'PLAN and APPLY'
on:
  push:
    branches:
    - main
    paths:
    - terraform**
    - .github/workflows/**

permissions:
  contents: read
  pull-requests: write
  id-token: write
env:
  AWS_REGION: us-east-1

jobs:
  plan-terraform:
    runs-on: ubuntu-latest
    name: PLAN
    steps:

    - name: "Configure AWS Providers"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      id: init
      working-directory: terraform
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      id: plan
      working-directory: terraform
      run: terraform plan -lock=false -out=plan.dev.out

    - name: Upload Plan File
      id: artifact
      uses: actions/upload-artifact@v3
      with:
        name: plan_dev
        path: terraform/plan.dev.out
        retention-days: 5

  apply-terraform:
    runs-on: ubuntu-latest
    name: APPLY
    needs: plan-terraform
    steps:

    - name: "Configure AWS Providers"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      id: init
      working-directory: terraform
      run: terraform init

    - name: Download Plan File
      uses: actions/download-artifact@v3
      with:
        path: terraform
        name: plan_dev
    
    - name: Terraform Apply
      id: apply
      working-directory: terraform
      run: terraform apply -auto-approve -lock=false plan.dev.out
