name: Test Timeout

on:
  workflow_dispatch: # Permite disparar o workflow manualmente

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # Define o timeout para 2 minutos
    steps:
      - name: Start a long-running process
        run: |
          echo "Starting a process that will take longer than 2 minutes..."
          sleep 150 # Aguarda 2 minutos e 30 segundos
          echo "Process completed"
